config/routes.rb
Rails.application.routes.draw do
  root "static_pages#main"
  get '/users/:id', to: "static_pages#main", as: 'user'
  get '/accounts/new/:user_id', to: "accounts#new", as: 'new_account'
  post '/categories/toggle/:id', to: 'categories#toggle', as: 'category_toggle'
  
  resources :transactions, only: [:edit, :update, :create, :destroy]
  resources :accounts, only: [:edit, :update, :create, :destroy] do
    resources :transactions, only: [:index, :new]
  end
  resources :categories
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def main
    @user = User.find_by_id(params[:id]) || nil
    @current_year = Time.now.year
    @user_accounts = Account.select { |u| u.user_id == @user.id } if @user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_controls.html.erb
<% if @account %>
  <%= button_tag "Add Transaction", 
                {'data-toggle' =>  "modal", 'data-target' => '#modal-window',
                class: "btn btn-primary", id: "add-transaction",
                :onclick => "$.ajax({url: `#{new_account_transaction_path @account}`})" } %>
<% end %>
<% if @user %>
  <%= button_tag "Categories", 
                {'data-toggle' =>  "modal", 'data-target' => '#modal-window',
                class: "btn btn-primary", id: "edit-categories",
                :onclick => "$.ajax({url: `#{categories_path}`})" } %>
<% end %>

app/views/static_pages/_modal_template.html.erb
<div id="modal-window" class="modal fade" tabindex="-1"
     role="dialog" aria-labelledby="modal-title" 
     aria-hidden="true">
</div>

app/views/static_pages/_year_section.html.erb
<section id="year-section">
  <% if @user %>
    Transactions year:&nbsp;<%= select_tag "year", options_for_select((2017..(@current_year + 1)), @current_year), :onchange => 'populate_transactions()'%>
  <% end %>
</section>

app/views/static_pages/main.html.erb
<div class="page-container">
  <div id="side-menu">
    <%= render 'users/users_panel' %>
    <%= render 'static_pages/year_section' %>
    <section id="accounts-list">
      <%= render 'accounts/accounts_list' %>
    </section>
    <section id="controls">
      <%= render 'static_pages/controls' %>
    </section>
    <%= render 'users/user_networth' %>
  </div>
  <div class="transactions-panel table-responsive" id="transactions-table">
  </div>
  <%= render 'static_pages/modal_template' %>
</div>