config/routes.rb
Rails.application.routes.draw do
  root "static_pages#main"
  get '/users/:id', to: "static_pages#main", as: 'user'
  get '/accounts/new/:user_id', to: "accounts#new", as: 'new_account'
  post '/categories/toggle/:id', to: 'categories#toggle', as: 'category_toggle'
  
  resources :transactions, only: [:edit, :update, :create, :destroy]
  resources :accounts, only: [:edit, :update, :create, :destroy] do
    resources :transactions, only: [:index, :new]
  end
  resources :categories
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope -> { order('lower(name)')}

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :background_color, length: { is: 7 }, 
                               format: { with: /#[0-9A-F]{6,6}/i }
  validates :foreground_color, length: { is: 7 }, 
                               format: { with: /#[0-9A-F]{6,6}/i }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include CategoriesHelper
  def index
    @categories = Category.all
    @disabled_categories = get_disabled_categories
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @disabled_categories = get_disabled_categories
    
    respond_to do |format|
      if @category.save
        format.html { render partial: 'categories/modal/category_row', :locals => {:category => @category} }
      else
        format.js { render(:status => 500, :json => @category.errors.full_messages)}
      end
    end
  end

  def edit
    @category = Category.find_by_id(params[:id])
  end

  def update
    @category = Category.find_by_id(params[:id])
    @disabled_categories = get_disabled_categories
    other = Category.find_by(name: 'Other')
    other_cannot_update = ["Cannot update the 'Other' category"] if @category.id == other.id
    
    respond_to do |format|
      if not other_cannot_update and @category.update(category_params)
        format.html { render partial: 'categories/modal/category_row', :locals => {:category => @category} }
      else
        format.js { render(:status => 500, :json => other_cannot_update || @category.errors.full_messages)}
      end
    end
  end

  def destroy
    category = Category.find_by_id(params[:id])
    transactions_with_category = Transaction.where(category_id: category.id)
    other = Category.find_by(name: 'Other')
    @disabled_categories = get_disabled_categories

    if category.id != other.id # don't allow to delete 'Other'
      transactions_with_category.each do |transaction|
        transaction.update_attribute(:category_id, other.id)
      end
      
      # Don't forget to remove the cookie
      if @disabled_categories.include?(category.id)
        @disabled_categories.delete(category.id)
        cookies.permanent[:disabled_categories] = @disabled_categories
      end

      category.destroy
    end
    
    @categories = Category.all
  end

  def toggle
    @categories = Category.all
    @disabled_categories = get_disabled_categories
    param_id = params[:id].to_i
    
    case param_id
    when 0 # Check all categories
      @disabled_categories = []
    when -1 # Uncheck all categories
      @disabled_categories = @categories.map(&:id)
    else # Toggling a category
      if @disabled_categories.include?(param_id)
        @disabled_categories.delete(param_id)
      else
        @disabled_categories << param_id
      end
    end

    cookies.permanent[:disabled_categories] = @disabled_categories
  end

  private
    def category_params
      params.permit(:name, :foreground_color, :background_color)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def get_disabled_categories
    disabled_categories = cookies.permanent[:disabled_categories] || []
    disabled_categories = disabled_categories.split('&').map(&:to_i) unless disabled_categories.is_a?(Array)
    disabled_categories
  end
end

app/views/categories/modal/_category_modal.html.erb
<div class="modal-dialog modal-dialog-centered modal-lg" role="document">
  <div class="modal-content" id="category-modal-content">
    <%= render 'categories/modal/modal_content' %>
  </div>
</div>

app/views/categories/modal/_category_row.html.erb
<tr id="category-row-<%= category.id %>">
  <td class="checkbox-column">
    <%= check_box_tag "enable_#{category.name.parameterize(separator: "_")}", 
                      category.id, 
                      !@disabled_categories.include?(category.id), 
                      class: 'category-checkbox',
                      :onchange => "$.ajax({ url: '#{category_toggle_path category.id}', type: 'POST' })" %>
  </td>
  <td><%= category.name %></td>
  <td><%= color_field_tag "fcolor-#{category.id}", category.foreground_color, disabled: true   %></td>
  <td><%= color_field_tag "bcolor-#{category.id}", category.background_color, disabled: true   %></td>
  <td class="actions-column">
    <% if category.id > 1 # Skip the 'Other' category %>
      <%= button_tag(type: 'button', 
                    class: 'btn btn-edit-category btn-warning',
                    :onclick => "$.ajax({url: '#{edit_category_path category}'})") do %>
        <i class="fa fa-pencil"></i>
      <%  end %>
      <%= button_tag(type: 'button', 
                    class: 'btn btn-delete-category btn-danger',
                    :onclick => "delete_category(#{category.id})") do %>
        <i class="fa fa-trash"></i>
      <%  end %>
    <% end %>
  </td>
</tr>

app/views/categories/modal/_edit_category_row.html.erb
<tr id="edit-category-row">
  <td class="checkbox-column"></td>
  <td><%= text_field_tag 'edit_category_name', @category.name, class: 'form-control', placeholder: "Cool Category" %></td>
  <td><%= color_field_tag 'edit_category_foreground_color', @category.foreground_color, 
                          class: 'form-control', onchange: "change_example_foreground()" %></td>
  <td><%= color_field_tag 'edit_category_background_color', @category.background_color, 
                          class: 'form-control', onchange: "change_example_background()" %></td>
  <td class="actions-column">
    <%= button_tag(type: 'button', 
                  class: 'btn btn-save-category btn-success',
                  :onclick => "save_category(#{@category.id})") do %>
      <i class="fa fa-save"></i>
    <%  end %>
    <%= button_tag(type: 'button', 
                  class: 'btn btn-cancel-category btn-danger',
                  :onclick => "cancel_creating_category(#{@category.id})") do %>
      <i class="fa fa-times-circle"></i>
    <%  end %>
  </td>
</tr>

app/views/categories/modal/_example_row.html.erb
<div id="example-section">
  <hr>
  <h4>Example:</h4>
  <table class="table example-table">
    <tbody>
      <tr id="example-row">
        <td>Date</td>
        <td>Name</td>
        <td>Details</td>
        <td>Cost</td>
        <td>Balance</td>
        <td>Rewards</td>
      </tr>
    </tbody>
  </table>
  <hr>
</div>

app/views/categories/modal/_modal_content.html.erb
<% provide(:modal_title, 'Categories') %>
<%= render 'shared_modal/header' %>
<div class="modal-body">
  <div class="table-responsive" id="categories-table">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Enabled</th>
          <th scope="col">Name</th>
          <th scope="col">Foreground</th>
          <th scope="col">Background</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody id="category-table-contents">
        <% @categories.each do |category| %>
          <%= render 'categories/modal/category_row', {category: category} %>
        <% end %>
      </tbody>
    </table>
  </div>
  <div>
    <%= button_tag(type: 'button', 
                  class: 'btn btn-info',
                  :onclick => "$.ajax({ url: '#{category_toggle_path 0}', type: 'POST', success: check_all_categories() })") do %>
      <i class="fa fa-check-square"></i> Check All
    <% end %>
    <%= button_tag(type: 'button', 
                  class: 'btn btn-warning',
                  :onclick => "$.ajax({ url: '#{category_toggle_path -1}', type: 'POST', success: uncheck_all_categories() })") do %>
      <i class="fa fa-square"></i> Uncheck All
    <% end %>
    <%= button_tag(type: 'button', 
                  class: 'btn btn-success',
                  id: 'new-category-button',
                  :onclick => "$.ajax({ url: '#{new_category_path}' })") do %>
      <i class="fa fa-plus"></i> Add Category
    <% end %>
  </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-success" data-dismiss="modal">Complete</button>
</div>