config/routes.rb
Rails.application.routes.draw do
  root "static_pages#main"
  get '/users/:id', to: "static_pages#main", as: 'user'
  get '/accounts/new/:user_id', to: "accounts#new", as: 'new_account'
  post '/categories/toggle/:id', to: 'categories#toggle', as: 'category_toggle'
  
  resources :transactions, only: [:edit, :update, :create, :destroy]
  resources :accounts, only: [:edit, :update, :create, :destroy] do
    resources :transactions, only: [:index, :new]
  end
  resources :categories
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  include TransactionsHelper

  def index
    @account = Account.find_by_id(params[:account_id])
    get_transaction_list_variables(params[:year], @account)
  end

  def new
    @transaction = Transaction.new
    @account = Account.find_by_id(params[:account_id])  
    @categories = Category.all
  end

  def create
    @account = Account.find_by_id(params[:account_id])
    @category = Category.find_by_id(params[:category_id])
    recurrence = params[:recurrence].to_i
    transactions = []
    time_now = (params[:transaction][:date] || Time.now).to_date
    end_of_year = time_now.end_of_year.to_date

    while time_now <= end_of_year
      t = Transaction.new(transaction_params)
      t.account = @account
      t.category = @category
      t.date = time_now # Override for recurrences throughout the loop
      transactions << t

      break if not t.valid? or recurrence == 0

      case recurrence
      when 1 # daily
        time_now += 1.day
      when 2 # weekly
        time_now += 1.week
      when 3 # bi-weekly
        time_now += 2.weeks
      when 4 # tri-weekly
        time_now += 3.weeks
      when 5 # monthly
        time_now += 1.month
      when 6 # bi-monthly
        time_now += 2.months
      else # no (or invalid) recurrence. Shouldn't get here in the first place
        break
      end
    end

    @transaction = transactions.first

    respond_to do |format|
      if @transaction.valid? 
        # Assume all transactions are valid and saved since they're duplicates
        transactions.each do |transaction|
          transaction.save
        end
        get_transaction_list_variables(@transaction.date.year, @account)
        @user_accounts = @user.accounts
        format.js { render :partial => 'transactions/apply_change' }
      else
        @categories = Category.all
        format.js { render :new }
      end
    end
  end

  def destroy
    @transaction = Transaction.find_by_id(params[:id])
    @account = @transaction.account
    get_transaction_list_variables(@transaction.date.year, @account)
    @user_accounts = @user.accounts
    respond_to do |format|
      if @transaction.destroy
        format.js { render :partial => 'transactions/apply_change' }
      end
    end
  end

  def edit
    @transaction = Transaction.find_by_id(params[:id])
    @account = @transaction.account
    @categories = Category.all
  end

  def update
    @transaction = Transaction.find_by_id(params[:id])
    @category = Category.find_by_id(params[:category_id])
    @transaction.update(transaction_params)
    @transaction.update_attribute(:category_id, @category.id) if @category
    @account = @transaction.account
    respond_to do |format|
      if @transaction.valid?
        get_transaction_list_variables(@transaction.date.year, @account)
        @user_accounts = @user.accounts
        @skip_jump = true # Don't jump to today's transaction
        format.js { render :partial => 'transactions/apply_change' }
      else
        @categories = Category.all
        format.js { render :edit }
      end
    end
  end

  private
    def transaction_params
      params.require(:transaction).permit(:date, :name, :details, :cost, :reward_amount)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def get_transaction_list_variables(year, account)
    @user = account.user
    @respective_transactions = account.transactions.where("cast(strftime('%Y', date) as int) = ?", year)
    @starting_balance = account.prev_years_balance(year)
    @starting_rewards_balance = account.prev_years_reward_balance(year)
    @categories = Category.all
  end
end

app/views/transactions/_apply_change.js.erb
$("#modal-window").modal('hide');
$("#transactions-table").html("<%= escape_javascript(render 'transactions/transaction_list') %>");
$("#accounts-list").html("<%= escape_javascript(render 'accounts/accounts_list') %>");
refresh_current_info('<%= @user.net_worth %>');
select_account(<%= @account.id %>);

app/views/transactions/_transaction_list.html.erb
<% running_balance = @starting_balance %>
<% running_rewards_balance = @starting_rewards_balance %>
<% latest_transaction = @respective_transactions&.select{|t| t.date <= Time.now }.last if @respective_transactions.first && @respective_transactions.first.date.year == Time.now.year %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Name</th>
      <th scope="col">Details</th>
      <th scope="col">Cost</th>
      <th scope="col">Balance</th>
      <% if @account.credit_card %>
        <th scope="col">Rewards</th>
        <th scope="col">Rewards Balance</th>
      <% end %>
      <th scope="col">Category</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody id="transactions-table-contents">
  <% @respective_transactions.each do |transaction| %>
    <% running_balance += transaction.transaction_cost %>
    <% running_rewards_balance += transaction.reward_amount %>
    <% transaction_category = @categories.detect{|c| c.id == transaction.category_id} %>
    <% classes = '' %>
    <% classes = 'hidden-transaction' if get_disabled_categories.include?(transaction_category.id) %>
    <% classes += ' today-transaction' if transaction == latest_transaction %>
    <tr id="transaction-<%= transaction.id %>" 
        <%= raw "class='#{classes}'" %>
        <%= raw "style='background-color: #{transaction_category.background_color}; color: #{transaction_category.foreground_color};'" unless transaction == latest_transaction %>>
      <td><%= transaction.date.to_date %></td>
      <td title="<%= transaction.name %>"><%= transaction.name %></td>
      <td title="<%= transaction.details %>"><%= transaction.details %></td>
      <td>$<%= transaction.transaction_cost(formatted: true) %></td>
      <td>$<%= number_with_precision(running_balance, precision: 2, delimiter: ',') %></td>
      <% if @account.credit_card %>
        <td><%= transaction.reward_amount %></td>
        <td><%= running_rewards_balance %></td>
      <% end %>
      <td><%= transaction_category.name %></td>
      <td>
        <%= button_tag(type: 'button', 
                      'data-toggle' =>  "modal", 'data-target' => '#modal-window',
                      class: 'btn btn-edit-transaction btn-warning',
                      :onclick => "$.ajax({url: '#{edit_transaction_path transaction}'})") do %>
          <i class="fa fa-pencil"></i>
        <%  end %>
        <%= button_tag(type: 'button', 
                      class: 'btn btn-delete-transaction btn-danger',
                      :onclick => "$.ajax({url: '#{transaction_path transaction}',type: 'DELETE'})") do %>
          <i class="fa fa-trash"></i>
        <%  end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<% if not @skip_jump %>
  <script>
  (() => { 
    var t = $('td:contains("<%= latest_transaction&.date&.strftime("%Y-%m-%d") %>")')[0]
    if (t) {
      t.scrollIntoView();
    } 
  })();
  </script>
<% end %>

app/views/transactions/edit.js.erb
$("#modal-window").html("<%= escape_javascript(render 'transactions/modal/edit_transaction_modal') %>");
focus_on('#transaction_name');

app/views/transactions/index.js.erb
$("#transactions-table").html(`
  <% if @respective_transactions.count > 0 %>
    <%= render 'transactions/transaction_list' %>
  <% else %>
    <div class="empty-transactions">There appears to be no transactions for this year!</div>
  <% end %>
`);

select_account(<%= @account.id %>);

$("#controls").html("<%= escape_javascript(render 'static_pages/controls') %>");

app/views/transactions/new.js.erb
$("#modal-window").html("<%= escape_javascript(render 'transactions/modal/new_transaction_modal') %>");
focus_on('#transaction_name');