config/routes.rb
Rails.application.routes.draw do
  root "static_pages#main"
  get '/users/:id', to: "static_pages#main", as: 'user'
  get '/accounts/new/:user_id', to: "accounts#new", as: 'new_account'
  post '/categories/toggle/:id', to: 'categories#toggle', as: 'category_toggle'
  
  resources :transactions, only: [:edit, :update, :create, :destroy]
  resources :accounts, only: [:edit, :update, :create, :destroy] do
    resources :transactions, only: [:index, :new]
  end
  resources :categories
end

app/models/account.rb
class Account < ApplicationRecord
  include ActionView::Helpers::NumberHelper
  
  belongs_to :user
  has_many :transactions,  dependent: :destroy 
  has_many :balances,  dependent: :destroy 

  validates :name, presence: true

  def prev_years_balance(year = Time.now.year)
    Balance.find_by(year: (year.to_i - 1), account_id: id)&.total_balance || 0 
  end

  def prev_years_reward_balance(year = Time.now.year)
    Balance.find_by(year: (year.to_i - 1), account_id: id)&.total_reward_balance || 0 
  end

  def current_balance(year: Time.now.year, formatted: false)
    last_year = prev_years_balance year
    if last_year
      balance = last_year
    else
      balance = 0
    end
    transactions_until_now = transactions.where("cast(strftime('%Y', date) as int) = ? AND date <= ?", year, Time.now)
    
    if formatted
      balance += transactions_until_now.sum { |t| t.transaction_cost }
      number_with_precision(balance, precision: 2, delimiter: ',')
    else
      balance += transactions_until_now.sum { |t| t.transaction_cost }
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
    @account = Account.new
    @user = User.find_by_id(params[:user_id])
  end

  def edit
    @account = Account.find_by_id(params[:id])
    @user = @account.user
  end

  def create
    cc_acct = params[:account][:account_type] == 'credit_card'
    loan_acct = params[:account][:account_type] == 'loan'
    @user = User.find_by_id(params[:user_id])

    @account = Account.new(
      name: params[:account][:name], 
      credit_card: cc_acct, 
      loan: loan_acct,
      user: @user
    )
    
    respond_to do |format|
      if @account.save
        @user_accounts = @user.accounts
        format.js
      else
        format.js { render :new }
      end
    end
  end

  def update
    @account = Account.find_by_id(params[:id])
    @account.name = params[:account][:name]

    respond_to do |format|
      if @account.save
        @user = @account.user
        @user_accounts = @user.accounts
        format.js
      else
        format.js { render :edit }
      end
    end
  end

  def destroy
    @account = Account.find_by_id(params[:id])
    @user = @account.user
    
    respond_to do |format|
      if @account.destroy
        format.js
      end
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_accounts_list.html.erb
<% if @user_accounts %>
  <% @user_accounts.each do |account| %>
    <%= form_with(url: account_transactions_path(account), 
                  remote: true, method: 'get', 
                  id: "form-account-#{account.id}") do |f| %>
      <div>
        <%= hidden_field_tag :year, @current_year %>
      </div>
      <%= f.submit "#{account.name} ($#{number_with_precision(account.current_balance, precision: 2, delimiter: ',')})", 
                    class: "btn btn-account btn-primary", id: "account-#{account.id}" %>
      <%= button_tag(type: 'button', 
                     'data-toggle' =>  "modal", 'data-target' => '#modal-window',
                     class: 'btn btn-edit-account btn-warning',
                     :onclick => "$.ajax({url: `#{edit_account_path account}`})") do %>
        <i class="fa fa-pencil"></i>
      <%  end %>
      <%= button_tag(type: 'button', 
                     class: 'btn btn-delete-account btn-danger',
                     :onclick => "delete_account(#{account.id})") do %>
        <i class="fa fa-trash"></i>
      <%  end %>
    <% end %>
  <% end %>
<% end %>
<% if @user %>
  <%= button_tag('data-toggle' =>  "modal", 
                 'data-target' => '#modal-window',
                 class: "btn btn-success", id: "add-account",
                 :onclick => "$.ajax({url: `#{new_account_path @user}`})") do %>
    <i class="fa fa-plus"></i> Add Account
  <% end %>
<% end %>

app/views/accounts/create.js.erb
$("#modal-window").modal('hide');

currently_selected = $("input.btn-success")[0];
$("#accounts-list").html("<%= escape_javascript(render 'accounts/accounts_list') %>");
<%# Need to make sure we re-select the account after the list was re-rendered %>
if (currently_selected) {
  select_account(currently_selected.id.slice(-1));
}

refresh_current_info('<%= @user.net_worth %>');

app/views/accounts/destroy.js.erb
currently_selected =$("input.btn-success")[0];
<%# If viewing this account's transactions, clear them out %>
if (currently_selected && currently_selected.id == 'account-<%= params[:id] %>') {
  $("#transactions-table").html("");
}
$("#form-account-<%= params[:id] %>").remove();
refresh_current_info('<%= @user.net_worth %>');

app/views/accounts/edit.js.erb
$("#modal-window").html("<%= escape_javascript(render 'accounts/modal/edit_account_modal') %>");
focus_on('#account_name');

app/views/accounts/new.js.erb
$("#modal-window").html("<%= escape_javascript(render 'accounts/modal/new_account_modal') %>");
focus_on('#account_name');

app/views/accounts/update.js.erb
$("#modal-window").modal('hide');
$("#accounts-list").html("<%= escape_javascript(render 'accounts/accounts_list') %>");
refresh_current_info('<%= @user.net_worth %>');
select_account(<%= @account.id %>);